#!/usr/bin/env bash
# Деплой mem0_local_server.py на HOST (VPS/deploy-host). Без секретов в git.
# Usage: ssh VPS_PROD 'bash -s' < scripts/apply_mem0_local_server.sh
#   или на сервере: bash /opt/gemma_agent/scripts/apply_mem0_local_server.sh

set -euo pipefail

MEM0_DIR="${MEM0_DIR:-/opt/mem0_local}"
GEMMA_ROOT="${GEMMA_ROOT:-/opt/gemma_agent}"
SRC="${GEMMA_ROOT}/scripts/mem0_local_server.py"
DEST="${MEM0_DIR}/mem0_server.py"
ENV_FILE="${MEM0_DIR}/.env"
GEMMA_ENV="${GEMMA_ROOT}/.env"

if [[ ! -f "$SRC" ]]; then
  echo "missing $SRC — git pull in $GEMMA_ROOT first" >&2
  exit 1
fi

mkdir -p "$MEM0_DIR"
cp "$SRC" "$DEST"

# OPENROUTER key from gemma .env (не печатать)
if [[ -f "$GEMMA_ENV" ]]; then
  OR_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$GEMMA_ENV" | head -1 | cut -d= -f2- | tr -d '\r' | sed 's/^["'\'' ]//;s/["'\'' ]$//')"
else
  OR_KEY=""
fi

{
  echo "# generated by apply_mem0_local_server.sh — do not commit"
  echo "MEM0_DB_PATH=${MEM0_DIR}/memory.db"
  echo "MEM0_LLM_REWRITE=false"
  echo "MEM0_LLM_COMPRESS=false"
  echo "MEM0_OPENROUTER_PROVIDER_ORDER=DeepSeek,baidu"
  echo "MEM0_OPENROUTER_PROVIDER_IGNORE=deepinfra"
  if [[ -n "$OR_KEY" ]]; then
    echo "OPENROUTER_API_KEY=${OR_KEY}"
  fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# restart uvicorn on 8001
PID="$(pgrep -f 'uvicorn mem0_server:app' || true)"
if [[ -n "$PID" ]]; then
  kill "$PID" || true
  sleep 1
fi

cd "$MEM0_DIR"
if [[ -x "${MEM0_DIR}/venv/bin/python" ]]; then
  PY="${MEM0_DIR}/venv/bin/python"
else
  PY="${GEMMA_ROOT}/venv/bin/python"
fi
nohup "$PY" -m uvicorn mem0_server:app --host 127.0.0.1 --port 8001 \
  >> "${MEM0_DIR}/mem0_server.log" 2>&1 &
sleep 2
CODE="$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8001/docs || echo 000)"
echo "mem0_local: deployed rewrite=off, /docs HTTP ${CODE}"
